### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=IntelliJ IDEA

###


### GET request to local server with query parameters

### GET request to Get a pharmacy by ID
GET http://localhost:8080/api/v1/admin/pharmacies?search=&status=All&page=0&size=12&sortBy=createdAt&sortDir=desc

### Unified Login - Customer
POST http://localhost:8080/api/v1/users/login
Content-Type: application/json

{
  "email": "senuja@gmail.com",
  "password": "sanuthma"
}



### Put request to update a user Profile
GET http://localhost:8080/api/v1/customers/profile
Authorization: Bearer temp-token-customer-8
Content-Type: application/json

### Update user profile
PUT http://localhost:8080/api/v1/customers/profile
Authorization: Bearer temp-token-customer-1
Content-Type: application/json

{
  "fullName": "Bavindu Updated Name",
  "phoneNumber": "+94-77-123-4567",
  "address": "123 Main Street, Colombo, Sri Lanka",
  "insuranceProvider": "Allianz Insurance",
  "allergies": ["Peanuts", "Shellfish"],
  "medicalConditions": ["Diabetes"]
}

### Get a user profile picture
POST http://localhost:8080/api/v1/customers/profile/upload-picture
Authorization: Bearer temp-token-customer-8
Content-Type: multipart/form-data

file="C:\Users\ASUS\Downloads\20250720_2310_image.png"

#### Get all user profiles
GET http://localhost:8080/api/v1/customers
Content-Type: application/json

### add a family member to the user profile
POST http://localhost:8080/api/members/family-members
Authorization: Bearer customer-token-5
Content-Type: application/json

{
  "name": "Jane Doe",
  "relation": "Sister",
  "age": 28,
  "medicalConditions": ["Asthma"]
}

### Delete a family member by ID
DELETE http://localhost:8080/api/members/family-members/18
Authorization: Bearer customer-token-5
Content-Type: application/json

### Get all family members of a user
GET http://localhost:8080/api/members/debug-auth
Authorization: Bearer customer-token-2


### Get all family members for debugging
GET http://localhost:8080/api/members/family-members
Authorization: Bearer customer-token-1


### Update customer profile
PUT http://localhost:8080/api/v1/customers/profile
Authorization: Bearer customer-token-3
Content-Type: application/json

{
  "username": "newusername",
  "fullName": "New Name",
  "email": "new@email.com",
  "phoneNumber": "1234567890",
  "dateOfBirth": "1990-01-01",
  "address": "123 Main St",
  "profilePictureUrl": "https://example.com/image.jpg",
  "allergies": [
    "Peanuts",
    "Shellfish"
  ],
  "medicalConditions": [
    "Asthma"
  ],
  "emergencyContactName": "Jane Doe",
  "emergencyContactPhone": "0987654321",
  "insuranceProvider": "ProviderX",
  "insuranceId": "INS-123456"
}